version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    command: npm start
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    command: serve -s public
