# This file configures how your application is built and run on Railway.
# It's optional but can be helpful to customize your environment.

[build]
  command = "npm ci"

[start]
  command = "npm run start"
