# Nixpacks Configuration
version = "1.0"

[build]
  dockerfile = "Dockerfile"

[build.packages]
  nodejs = "18.x"

[build.environment]
  NODE_ENV = "production"

[build.script]
  install = ["npm install --production"]
  start = ["npm run start"]

[deploy]
  command = "npm start"
